theme: jekyll-theme-cayman
title: "The `povcalnet` Stata command"
description: "Stata client to the Povcalnet API"
baseurl: "/povcalnet" # the subpath of your site, e.g. "/blog"
url: "https://worldbank.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
#logo: "/images/so-simple-site-logo.png" # path of site logo, e.g. "/assets/images/logo.png"
